# Base image.
FROM node:22.3.0-alpine

# Set evironment variables.
ENV LANG=C.UTF-8
ARG NEXTJS_PORT
ARG NEXTJS_SRC_DIR

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY ./src/${NEXTJS_SRC_DIR}/package.json .
#COPY ./src/ninja-recipes/package.json .

# Install packages.
RUN npm install

# Copy directory.
COPY ./src/${NEXTJS_SRC_DIR} .
#COPY ./src/ninja-recipes .

# Document exposed port.
EXPOSE ${NEXTJS_PORT}

# Start app.
ENTRYPOINT [ "npm", "run", "dev" ]