services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx_${NEXTJS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html
    #env_file:
    #  - ./.env

  nextjs-app:
    image: ${NEXTJS_IMAGE_NAME}:1.0.0
    build:
      dockerfile: Dockerfile.dev
      args:
        NEXTJS_APP_NAME: ${PROJECT_NAME}
        NEXTJS_PORT: ${NEXTJS_PORT}
        NEXTJS_SRC_DIR: ${NEXTJS_SRC_DIR}
    command: sh -c "npm run dev && json-server --watch ./_data/db.json --port 4000"
    container_name: ${NEXTJS_CONTAINER_NAME}
    restart: unless-stopped
    #ports:
    #  - ${NEXTJS_PORT_OUT}:${NEXTJS_PORT}
    volumes:
      - ./src/${NEXTJS_SRC_DIR}:/app
      - next_dir:/app/.next
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    #env_file:
    #  - .env
    depends_on:
      - nginx

volumes:
  next_dir:
  node_modules: