# Base image.
FROM node:22.3.0-alpine

# Set evironment variables.
ENV LANG=C.UTF-8

# Arguments In.
ARG NEXTJS_PORT
ARG NEXTJS_SRC_DIR

# Set up working directory.
WORKDIR /app

# Copy package.json file to working directory.
COPY ./src/${NEXTJS_SRC_DIR}/package.json .

# Install packages.
RUN npm install

# Install json-server
RUN npm install -g json-server

# Copy directory.
COPY ./src/${NEXTJS_SRC_DIR} .

# Document exposed port.
EXPOSE ${NEXTJS_PORT}

# Start app.
#ENTRYPOINT [ "npm", "run", "dev" ]
#ENTRYPOINT [ "npm", "run", "dev", "&&", "json-server", "--watch", "./_data/db.json", "--port", "4000" ]